### ISSUE TITLE
Feature Request: Ambience Extras compatibility

### ISSUE THREAD

**Issue by Duatao7055** [jredfox/menulib#16]
Compatibility with Ambience Extras for changing to different main menus would be pretty cool, if possible, since it adds its own menu music event. Compatibility would allow for events with different main menus, i.e. betweenlands music for the betweenlands main menu and vanilla minecraft music for the base main menu. I know your mod seems to do this for base vanilla music, but Ambience Extras handles music in a way that is not compatible with your mod.

**Comment by jredfox** [comment]
ok I haven't looked at this in a long time most likely it's an asm incompatibility issue.

**Comment by jredfox** [comment]
the issue is the forge apis are so broken with asm and even their own core systems that it is difficult to add compatibility. 

*I am re-writing all my libraries for my mod loader and I may make a forge port maybe then I will look into mod incompatibilities* I have been ill the past 3 months but, hopefully will get back into coding it

**Comment by jredfox** [comment]
I will tell you what. I will look into if I can see if I can cleanup the code within a couple days if  I can I will fix this issue, add an IMenu event to make your plugin easier, and fix the couple issues I already know exist I just forgotten what they were and have to figure that out again

**Comment by Duatao7055** [comment]
Alright, thank you very much for your responses and help. I hope you feel better, since you say you've been sick. I'm going to go do other things. Also, when I say finish learning java, I mean that I barely started learning the basics, and should probably learn more to write proper syntax and learn how to not make a crappy mod.

**Comment by jredfox** [comment]
hey what exactly was wrong with Ambience mod? did it not run their music in their menu?

**Comment by jredfox** [comment]
ok I found out I replace the music ticker method but, I still won't know if only editing it will fix said issue since you wouldn't describe what the issue was nor can I reproduce it

**Comment by jredfox** [comment]
try the jar I send you in a dm on discord

**Comment by jredfox** [comment]
you didn't explain your issue. This isn't a bug it's a feature request. I thought you meant that it wasn't playing music in their custom main menus
