### ISSUE TITLE
Feature Request: Changing menu screen based on last entered dimension

### ISSUE THREAD

**Issue by Duatao7055** [jredfox/menulib#17]
Pretty much the title. I would like this because I'm working on a modpack that focuses on immersion, and this just further adds to that. I want the ability to have the game load up and the main menu shows a menu I specified based on the last dimension I was in, so I can show the betweenlands main menu if the last dimension I was in was the betweenlands, and the overworld menu if the last dimension I was in was the overworld.

**Comment by jredfox** [comment]
menus are not dimension specific. You can create a simple plugin for it. I believe all you need to do is subscribe to an event either by me and forge and call my menu registry to switch the menu to whatever your plugin stores it as. But, Why would you want to do this not all menus are dimension specific. You could even write a plugin to create custom menus with this

**Comment by Duatao7055** [comment]
I want to do this because I'm trying to create a modpack that is immersive with a lot of little immersive details. I'm looking to change menu screens based on the last dimension the player was in, and create custom menus using custom main menu for each dimension. I have no idea where I would even start to create a plugin or something to do this, which is why I asked for an implementation of this in the mod. But I guess I'll just have to start learning :).

**Comment by jredfox** [comment]
custom main menu to create the menus. Then you write code to do what you want. You have to store your client's last dimension using a forge event Minecraft.getMinecraft().thePlayer.world.providerId or something like that. After that it's simply calling MenuRegistry.setMenu(IMenu). Now an IMenu needs to get registered in preinit and you can set your menu differently based on what dimension it is. In order to do this you need java.

**Comment by Duatao7055** [comment]
Ok then, thanks for the tip. Time to finish learning java

**Comment by jredfox** [comment]
it's basic java I told you most of what you needed to do. This mod was for other mods to add their custom menus to an array not to write plugins. 

I wouldn't recommend always using this behavior on startup what if a mod adds in a menu that's not a dimension specific? Also what if a user wants to change the menu after it's set? good luck with your mod

**Comment by jredfox** [comment]
O you will also have to serialize the dimension id if you want to do this on startup through either forge's config file or my ConfigLine objects. Save whenever your menu opens or if you want it safer whenever the player changes a dimension

**Comment by jredfox** [comment]
thinking about it  on world close event just call MenuRegistry.setMenu(ResourceLocation index) . You will have to store one menu for each dimension either by user config or by you. From there your done. Now if you wanted to add menus you would call my main api found on my menu lib curseforge.
